### PR TITLE
Carousel version of the main page [carousel-dev]

### PR DESCRIPTION
**Pull request by jakubcerveny**
I felt that the main page in #3 is slightly overloaded and there was an idea of using a carousel, so here is my attempt to do that.

The three slides are just an example, they could be changed.

Also the slide height of 400px may be too much, maybe 350-380px would be better.

Screenshot from 2021-04-16 16-27-59

### CODE REVIEW

**Comment by tzanio** [comment]
OK, I took a look and made several changes that look better to me.

@jakubcerveny can you take a look and fix them or let me know if you want to revert some of them?

I also deployed this version to https://glvis.org for testing purposes.

@v-dobrev, @tomstitt and @kanye-quest -- what do you think? do you like this or the #3 version (or something else) more? can you help improve it?

Tzanio

**Comment by tzanio** [comment]
Screen Shot 2021-04-18 at 4 52 13 PM

**Comment by jakubcerveny** [comment]
I think it looks great!

One minor issue, maybe just on my setup (Firefox), when I hover over the "Use web version" button, it disappears. The hover style is probably just white, even though I'm not sure why. Should I try to tweak the style?

**Comment by tzanio** [comment]
> The hover style is probably just white, even though I'm not sure why. Should I try to tweak the style?

Yes, please do!

**Comment by v-dobrev** [comment]
This version looks good to me too. 👍 

One small thing: can we make the left and right arrows in the carousel fade out completely when mouse is not close to them? Right now they fade out partially and still cover a bit of the 2nd and 3rd image.

**Comment by jakubcerveny** [comment]
I changed the class of the "Use web version" button (didn't figure out how to stop the old one from disappearing on Firefox).
I'm not sure it's good to completely hide the carousel arrows, but at least I reduced their opacity when inactive...

Screenshot from 2021-04-19 18-39-26

**Review by tzanio — APPROVED** [review]
Thank you @jakubcerveny

**Review by tomstitt — APPROVED** [review]
I like it!

**Comment by tzanio** [comment]
Folks seems to generally like this, so lets merge and discuss any outstanding issues in #3

**Pull request merged**
