### PR TITLE
Website updates for the Web and Jupyter versions

### PR DESCRIPTION
**Pull request by tzanio**

### CODE REVIEW

**Comment by tzanio** [comment]
@tomstitt and @kanye-quest can you take a look at this update to the GLVis pages to highlight the Web and Jupyter versions?

I am sure this can be improved, so please feel free to make any changes you see fit 😁 

For your convenience I deployed this version to https://glvis.org/.

Thank you 🙏 

Tzanio

**Comment by tomstitt** [comment]
~~Besides the possible switch to https://mybinder.org/v2/gh/GLVis/pyglvis/HEAD?filepath=examples as the Jupyter link~~ (already done) this looks great to me! You could mention that the pyglvis examples use PyMFEM but I don't think that's necessary. 

I especially like that the images under `Desktop, Web and Jupyter Versions` show the same plot but specific to their runtime.

**Review by tomstitt — APPROVED** [review]

**Comment by publixsubfan** [comment]
The website looks good to me (although I'm sure we could add some more docs on the website/Jupyter features later), but it seems some of those saved stream files are a little on the heavy side. Is there another way to store these files online, but outside of git?

I would have suggested putting them in Git LFS, but apparently Github Pages doesn't support pulling files from there.

**Comment by tzanio** [comment]
>  Is there another way to store these files online, but outside of git?

I agree, but I couldn't figure out a better solution. I'm definitely open to suggestions.

**Comment by tomstitt** [comment]
> > Is there another way to store these files online, but outside of git?
> 
> I agree, but I couldn't figure out a better solution. I'm definitely open to suggestions.

We could gzip the save files and inflate them after they are fetched or we could use lfs and update the links to point at the files on github (something like `http://raw.githubusercontent.com/glvis/web/master/data/*.saved`)

**Comment by tzanio** [comment]
People seem to like this version 👍 

If I don't hear any objections from @jakubcerveny, @v-dobrev, @tomstitt or @kanye-quest, I'll merge it tomorrow (it is already deployed).

**Pull request merged**
