### PR TITLE
Website changes for glvis-4.3

### PR DESCRIPTION
**Pull request by tzanio**
### TODO
- [x] Update version number in `index.md`, `download.md` and `news.md`
- [x] Update list of contributors
- [x] Update "features"
- [x] Update "options and use"
- [x] Fix code line references
- [x] Create bit.ly shortlink (https://bit.ly/glvis-4-3)
- [x] Add new items to the Gallery, e.g. from quadrature visualization?
- [x] Update the Windows binary
- [x] Update the size and SLOC for this version in `download.md`
- [x] Remove link to doxygen docs
- [ ] Update the Mac binary

### CODE REVIEW

**Comment by tzanio** [comment]
@justinlaughlin and @najlkin -- take a look at the URL I listed for you in the "About" page and feel free to change it

**Comment by tzanio** [comment]
One option for image to add to the Gallery:

LOR QuadFunc 2

**Comment by najlkin** [comment]
Another option would be [this one](https://github.com/GLVis/glvis/pull/286#issuecomment-2234057064) redone with the improved cplane=2 👍 , if it was made with it.

**Comment by najlkin** [comment]
That links to code in "Options and use" are broken pointing to something totally different. They should be fixed to match current master (but that is a moving target 🎯 ...), or fixed to point to a certain commit/tag, or removed completely 🤔 
Update: Bad links are also in "Mesh formats" and "Parallel visualization".

**Comment by tzanio** [comment]
> Another option would be [this one](https://github.com/GLVis/glvis/pull/286#issuecomment-2234057064) redone with the improved cplane=2 👍 , if it was made with it.

Do you mean something like this?

Screenshot 2024-08-06 at 8 16 17 AM

**Comment by najlkin** [comment]
Regarding the code line references, I think the best way would be to point them to the tag of the corresponding MFEM release if they are really necessary, but most of them are actually not as they come from the early days, when things were evolving abruptly, but the code is more modestly changing now, so they can be copied out of the code and their change is not much anticipated any time soon. Another thing is that the code is more complex than it used to be, so asking a basic user to understand it is a bit over the top 🤔 . Will you take care of it, @tzanio ?

**Comment by tzanio** [comment]
> That links to code in "Options and use" are broken pointing to something totally different. They should be fixed to match current master

Fixed in https://github.com/GLVis/web/pull/12/commits/c763a59093d7ab92c1ddb22f797a3d4cf78150e1

**Comment by tzanio** [comment]
> Bad links are also in "Mesh formats" and "Parallel visualization".

Fixed in https://github.com/GLVis/web/pull/12/commits/75c00af4c2f542dcc9354ca0305804d23f4c5fa3

**Comment by najlkin** [comment]
> > Bad links are also in "Mesh formats" and "Parallel visualization".
> 
> Fixed in [75c00af](https://github.com/GLVis/web/commit/75c00af4c2f542dcc9354ca0305804d23f4c5fa3)

That one is mine 😄 , did you push it?

**Comment by tzanio** [comment]
Oh, it should have been: https://github.com/GLVis/web/pull/12/commits/c5878abe48c8e5a27d64ffb839e0c3c337c973c2

**Comment by najlkin** [comment]
Hmm, it will get broken again when someone adds something to the examples. How about using `v4.7` instead of `master`? In the worst case, it will be outdated, but not broken...

**Comment by tzanio** [comment]
> How about using `v4.7` instead of `master`?

Sure, feel free to change it

**Comment by najlkin** [comment]
I did the same for GLVis, so they are "future" links 😉 .

**Review by najlkin — APPROVED** [review]

**Review by justinlaughlin — APPROVED** [review]

**Pull request merged**
